services:
  bsl-hub-app:
    build: .
    container_name: bsl-hub-app
    env_file: ./.env
    ports:
      - "4000:4000"
    restart: unless-stopped

networks:
  default:
    external: true
    name: hub-network
